# Generated by Django 4.2.9 on 2024-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorganizationmessage',
            name='user_role',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsuppliermessage',
            name='user_role',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
