# Generated by Django 4.2.9 on 2024-06-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_id', models.TextField()),
                ('price_id', models.TextField()),
                ('model_name', models.CharField(max_length=10)),
                ('model_price', models.IntegerField()),
                ('billing_period', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to='authentication.systemadmin')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_subscriptions', to='authentication.systemadmin')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionModelFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_features', to='authentication.systemadmin')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='subscription_models.subscriptionmodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_subscription_features', to='authentication.systemadmin')),
            ],
            options={
                'unique_together': {('feature', 'model')},
            },
        ),
    ]
