# Generated by Django 4.2.9 on 2024-06-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_otp_user_organization_logo_url_otp_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='email',
            new_name='user',
        ),
    ]
