# Generated by Django 4.2.9 on 2024-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_payment_id_alter_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
