# Generated by Django 4.2.9 on 2024-07-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_payment_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='organization',
        ),
    ]
