# Generated by Django 4.2.9 on 2024-07-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_models', '0002_alter_subscriptionmodel_model_id_and_more'),
        ('subscriptions', '0004_rename_user_subscription_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription_models.subscriptionmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription'),
        ),
    ]
