# Generated by Django 4.2.9 on 2024-06-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalInvoiceFormat',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='TemplateMapping',
            fields=[
            ],
        ),
    ]
